require("core.plugins")
require("core.mappings")
require("core.colors")
require("core.configs")

-- plugins
require("plugins.color")
require("plugins.neotree")
require("plugins.lualine")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.cmp")
require("plugins.mason")
require("plugins.telescope")
require("plugins.nullls")
require("plugins.autopairs")
require("plugins.comment")
require("plugins.indent")
require("plugins.buffer")
require("plugins.gitsigns")
require('plugins.toggleterm')
